name: LLM RAG - CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ingest sample and run tests (no API key)
        run: |
          mkdir -p data
          echo "This is a tiny test document about Microsoft 365 governance and secure collaboration." > data/seed.txt
          python rag.py ingest --data data --store store
          python -m pytest -q
