name: Weekly RAG Research Scraper (10 new)

on:
  schedule:
    - cron: "0 13 * * 1"   # Every Monday 8:00 AM America/Chicago
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      PYTHONDONTWRITEBYTECODE: "1"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper (10 new items)
        run: |
          python scripts/news_scraper.py --outdir data/news --limit 10

      - name: Show results
        run: |
          echo "== data/news =="
          ls -Rla data/news || true
          echo "== manifest preview =="
          head -n 200 data/news/manifest.json || true

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Weekly RAG research: +10 new articles → data/news + manifest [skip ci]" || echo "Nothing to commit"
          git push
