name: RAG Demo

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build questions.json
        run: |
          python scripts/build_questions.py

      - name: Ingest documents
        run: |
          python rag.py ingest --data "data" --store "store"

      - name: Run ask for all questions and build answers_multi.json
        env:
          STORE: "store"
        run: |
          python scripts/build_answers_multi.py

      - name: Build single latest answers.json for default display
        run: |
          # Take the first entry from answers_multi.json and write to answers.json
          python - <<'PYCODE'
          import json, pathlib
          multi = json.loads(pathlib.Path("answers_multi.json").read_text(encoding="utf-8"))
          latest = multi[0] if multi else {"question":"(none)","answer":"(no answer)","sources":[]}
          pathlib.Path("answers.json").write_text(json.dumps(latest, ensure_ascii=False, indent=2), encoding="utf-8")
          PYCODE

      - name: Show artifacts (debug)
        run: |
          echo "----- questions.json -----"
          cat questions.json || true
          echo "----- answers_multi.json (first 200 lines) -----"
          sed -n '1,200p' answers_multi.json || true
          echo "----- answers.json -----"
          cat answers.json || true

      - name: Commit generated artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add questions.json answers_multi.json answers.json
          git commit -m "Update Q&A artifacts [ci skip]" || echo "No changes"
          git push
