name: RAG Demo
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ingest documents
        run: |
          python rag.py ingest --data "data" --store "store"

      - name: Ask and build answers.json (robust)
        env:
          QUESTION: "What does the documentation say?"
          STORE: "store"
        run: |
          python scripts/build_answers_json.py

      - name: Show artifacts (debug)
        run: |
          echo "----- exit code shown above if failed -----"
          echo "----- answer.txt (first 200 lines) -----"
          sed -n '1,200p' answer.txt || true
          echo "----- answers.json -----"
          cat answers.json || true

      - name: Commit answers.json + answer.txt
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add answers.json answer.txt
          git commit -m "Update answers.json (robust parse) [ci skip]" || echo "No changes"
          git push
