name: RAG Demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run ingestion
      run: |
        python rag.py ingest --data "data" --store "store"

    - name: Run query example
      run: |
        python rag.py query --store "store" --question "What is Retrieval-Augmented Generation?"
